# Graphics
USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3

# Gralloc
BOARD_USES_EXYNOS5_COMMON_GRALLOC := true
TARGET_USES_GRALLOC1_ADAPTER := true

# (G)SCALER
BOARD_USES_SCALER := true

# Samsung LSI
TARGET_USES_UNIVERSAL_LIBHWJPEG := true

## ION
TARGET_USES_ION := true

##
## Samsung LSI Graphics
##
### Buffers
BOARD_USE_ANB_OUTBUF_SHARE := true
BOARD_USE_IMPROVED_BUFFER := true
BOARD_USE_NON_CACHED_GRAPHICBUFFER := true


