# Recovery
TARGET_OTA_ASSERT_DEVICE := gta3xlwifi
BOARD_HAS_DOWNLOAD_MODE := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SUPPRESS_SECURE_ERASE := true

TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/recovery/recovery.fstab
#TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/rootdir/fstab.exynos7885
